version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/app/data # SQLite
    command: sh -c "npm install && npm run dev"
